
package edu.umg.dw.web.cliente.dominio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioProveedoresService", targetNamespace = "http://sw.dw.umg.edu/", wsdlLocation = "file:/Users/fcastellanos/Projects/aseguradora/src/main/java/edu/umg/dw/web/cliente/ServicioProveedores.wsdl")
public class ServicioProveedoresService
    extends Service
{

    private final static URL SERVICIOPROVEEDORESSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOPROVEEDORESSERVICE_EXCEPTION;
    private final static QName SERVICIOPROVEEDORESSERVICE_QNAME = new QName("http://sw.dw.umg.edu/", "ServicioProveedoresService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/fcastellanos/Projects/aseguradora/src/main/java/edu/umg/dw/web/cliente/ServicioProveedores.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOPROVEEDORESSERVICE_WSDL_LOCATION = url;
        SERVICIOPROVEEDORESSERVICE_EXCEPTION = e;
    }

    public ServicioProveedoresService() {
        super(__getWsdlLocation(), SERVICIOPROVEEDORESSERVICE_QNAME);
    }

    public ServicioProveedoresService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOPROVEEDORESSERVICE_QNAME, features);
    }

    public ServicioProveedoresService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOPROVEEDORESSERVICE_QNAME);
    }

    public ServicioProveedoresService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOPROVEEDORESSERVICE_QNAME, features);
    }

    public ServicioProveedoresService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioProveedoresService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioProveedores
     */
    @WebEndpoint(name = "ServicioProveedoresPort")
    public ServicioProveedores getServicioProveedoresPort() {
        return super.getPort(new QName("http://sw.dw.umg.edu/", "ServicioProveedoresPort"), ServicioProveedores.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioProveedores
     */
    @WebEndpoint(name = "ServicioProveedoresPort")
    public ServicioProveedores getServicioProveedoresPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sw.dw.umg.edu/", "ServicioProveedoresPort"), ServicioProveedores.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOPROVEEDORESSERVICE_EXCEPTION!= null) {
            throw SERVICIOPROVEEDORESSERVICE_EXCEPTION;
        }
        return SERVICIOPROVEEDORESSERVICE_WSDL_LOCATION;
    }

}
