
package edu.umg.dw.web.cliente.dominio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioProveedores", targetNamespace = "http://sw.dw.umg.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioProveedores {


    /**
     * 
     * @param peticionConsultaPaciente
     * @return
     *     returns edu.umg.dw.web.cliente.dominio.RespuestaConsultaCobertura
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarCoberturaPaciente", targetNamespace = "http://sw.dw.umg.edu/", className = "edu.umg.dw.web.cliente.dominio.ConsultarCoberturaPaciente")
    @ResponseWrapper(localName = "consultarCoberturaPacienteResponse", targetNamespace = "http://sw.dw.umg.edu/", className = "edu.umg.dw.web.cliente.dominio.ConsultarCoberturaPacienteResponse")
    public RespuestaConsultaCobertura consultarCoberturaPaciente(
        @WebParam(name = "peticionConsultaPaciente", targetNamespace = "")
        PeticionConsultaPaciente peticionConsultaPaciente);

    /**
     * 
     * @return
     *     returns edu.umg.dw.web.cliente.dominio.RespuestaListadoProveedores
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerProveedores", targetNamespace = "http://sw.dw.umg.edu/", className = "edu.umg.dw.web.cliente.dominio.ObtenerProveedores")
    @ResponseWrapper(localName = "obtenerProveedoresResponse", targetNamespace = "http://sw.dw.umg.edu/", className = "edu.umg.dw.web.cliente.dominio.ObtenerProveedoresResponse")
    public RespuestaListadoProveedores obtenerProveedores();

}
